apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-server
  name: admin-server
  namespace: weblogic
spec:
  ports:
  - name: tcp-7001
    port: 7001
    protocol: TCP
    targetPort: 7001
  - name: tcp-8453
    port: 8453
    protocol: TCP
    targetPort: 8453
  selector:
    app: admin-server
  type: ClusterIP
