apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: weblogic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Dweblogic.StdoutDebugEnabled=true
        - name: TZ
          value: Asia/Shanghai
        - name: PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: wlsecret
              optional: false
        - name: USER
          valueFrom:
            secretKeyRef:
              key: username
              name: wlsecret
              optional: false
        image: gurongyun/weblogic:12.2.1.3-domain
        imagePullPolicy: Always
        name: admin-server
        ports:
        - containerPort: 7001
          name: tcp-7001
          protocol: TCP
        - containerPort: 8453
          name: tcp-8453
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /weblogic/ready
            port: 7001
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1600m
            memory: 2Gi
          requests:
            cpu: 400m
            memory: 512Mi
      imagePullSecrets:
      - name: admin-secret
      restartPolicy: Always
      