apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: managed-server
  namespace: weblogic
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  selector:
    matchLabels:
      app: managed-server
  serviceName: managed-server
  template:
    metadata:
      annotations:
      labels:
        app: managed-server
    spec:
     containers:
      - command:
        - startManagedServer.sh
        env:
        - name: JAVA_OPTIONS
          value: -Dweblogic.StdoutDebugEnabled=true
        - name: MANAGED_SERV_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: USER_MEM_ARGS
          value: -Xms64m -Xmx256m
        - name: TZ
          value: Asia/Shanghai
        - name: PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: wlsecret
              optional: false
        - name: USER
          valueFrom:
            secretKeyRef:
              key: username
              name: wlsecret
              optional: false
        image: 10.10.101.175/library/weblogic:12.2.1.3-domain
        imagePullPolicy: Always
        name: managed-server
        ports:
        - containerPort: 8001
          name: tcp-8001
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /weblogic/ready
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
      imagePullSecrets:
      - name: admin-secret
      restartPolicy: Always
  updateStrategy:
    type: RollingUpdate
